### ISSUE TITLE
The section called ''Reinitialize the MAC address of all network cards" is missing

### ISSUE THREAD

**Issue by sudo-art** [UPB-FILS-SdE2/questions#1]
Hello! 

As the title suggests, the section you have demanded us to check is not there. I have attached a photo below to have a clear idea what I'm talking about.

Thank you for your help !

![dref](https://user-images.githubusercontent.com/61539411/110435760-13d70e00-80bc-11eb-8fc9-b431d238f010.png)

**Comment by alexandruradovici** [comment]
Most probably you have a newer version of VirtualBox, the settings shown here are all right.
