### ISSUE TITLE
 [USO] <INCOMPREHENSIBLE ERRORS>

### ISSUE THREAD

**Issue by so308il** [UPB-FILS-SdE2/questions#100]
![err1](https://github.com/UPB-FILS-SdE2/questions/assets/96748234/dabd1ce7-74be-4af8-93f3-05b61fd8b10d)
![err2](https://github.com/UPB-FILS-SdE2/questions/assets/96748234/fe8b7ba6-bd3a-4d81-9cfb-b97f9e050814)

I met these  two errors the first one told me that there is no file ierarhie1.txt and this file originally didn't exist in the homework .And the second one was about : the PS1 environment variable was not correctly configured according to the specified colors, it is not persistent or does not have the value set in the prompt.txt file. 

Answer in : English or French 
thanks in Advance !

**Comment by Cristiana959** [comment]
You don't have to take these errors into consideration as they aren't part of your tasks. You can skip them and continue with the homework

**Comment by so308il** [comment]
**the punctaj maximum is 100 or 80 ?**
