### ISSUE TITLE
[webserver] econnrefused

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#101]
I keep having this problem when the tests are run
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/a0418a0a-b244-4212-a57a-dc385fad06c7)
Is it a problem with my code?

**Comment by petrescucatalin** [comment]
I have the same problem when I run the tests

**Comment by alexandruradovici** [comment]
It seems that the checker tries to use IPv6, trying now.

**Comment by alexandruradovici** [comment]
I have update the tests, instead of connecting to localhost, now it connects to 127.0.0.1.
