### ISSUE TITLE
[webserver] different test result

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#102]
I tried to run the get env test manually: I have the script in my project and I sent the headers with the environment values with my request using Postman. The output appears to be the same after execution, yet the test result is 'wrong message'. 
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/7db687a4-8535-4e85-92a5-2e9b11adca13)
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/3e286b88-062e-4c04-aa7b-5310160fb9ad)

**Comment by mihaicostin34** [comment]
I have corrected my code and now the contents and the headers are sent correctly (there was a mistake in my code before) , yet I have the same problem for multiple tests

**Comment by alexandruradovici** [comment]
Make sure you handle correctly subsequent queries and parallel queries.
