### ISSUE TITLE
[webserver] "-> success" but tests not passed

### ISSUE THREAD

**Issue by vladgabrielneculai** [UPB-FILS-SdE2/questions#104]
Hello,

I don't understand why I get the "-> success" message for the first tests but these tests are not passed.

<img width="828" alt="Screenshot 2023-06-19 at 16 27 02" src="https://github.com/UPB-FILS-SdE2/questions/assets/81146225/9ce9f5b0-6633-4410-ae8c-07137cc498a4">

What should I do in this situation?

**Comment by alexandruradovici** [comment]
The server sends the correct data, but the server logs are not correct.
