### ISSUE TITLE
[rustybox] autograding.json problem

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-SdE2/questions#106]
Autograding.json's tests are broken.

Instead of cd'ing into `rustybox-tests`, each graded test cd's into `tests` and it doesn't even get to running the compiled rust binary.

Is this a problem on my side or not?

**Comment by alexandruradovici** [comment]
I think we fixed it. Please push another commit to try it out.

**Comment by popescuatopg** [comment]
For me it's fixed, thanks!
