### ISSUE TITLE
[rustybox] Unable to pass tests specifically for 'cat' command despite success with terminal commands

### ISSUE THREAD

**Issue by RaresMihai24** [UPB-FILS-SdE2/questions#107]
Hello, when I run "cargo run --bin rustybox cat filename.txt" it prints the expected output but when I try to pass the test by terminal command using "cargo run --bin rustybox-tests/verify/cat/cat_simple.sh" there is no output to the terminal. Done other several tests(for pwd/echo) and both methods work without any issues
![image](https://github.com/UPB-FILS-SdE2/questions/assets/126671528/584d5656-175a-4482-a8cc-b6232be48564)
![image](https://github.com/UPB-FILS-SdE2/questions/assets/126671528/fc7b4ce3-e692-490a-a499-ff1ea4811f25)

**Comment by alexandruradovici** [comment]
Please take a look at `autograder.json` to see how to run the tests. You should be able to run all of them by using the`run_all.sh` without parameters. 

Make sure you install your crate using

```shell
cargo install --path .
```

**Comment by RaresMihai24** [comment]
![image](https://github.com/UPB-FILS-SdE2/questions/assets/126671528/2492caf8-b252-46e9-8f20-868bd4113d21)
run_all.sh does it's job, those specific tests don't, passed only cat error but no succes with cat simple and cat triple even if they should work as I tested by cat command in the terminal

**Comment by alexandruradovici** [comment]
Most probably they do not work. If you oush your homework, we can take a look at what autograder does and give you some feedback.

**Comment by RaresMihai24** [comment]
I pushed my homework, if I put the same text from the cat_simple.sh for example, it prints without any issues the text from the file, even if I specify the name of the file or if I put as a parameter the whole address(initially I thought that was the issue)

**Comment by alexandruradovici** [comment]
You have to print the exact contents of the file. You are using `println!` that adds a new line at the end. Using `print!` should fix the issue.

**Comment by RaresMihai24** [comment]
The print! indeed fixed "the issue", I'll try to be more cautious next time, thanks a lot :)
