### ISSUE TITLE
[rustybox] I have a problem with autogradel

### ISSUE THREAD

**Issue by Edy1504** [UPB-FILS-SdE2/questions#108]
When I load the code via git push I don't get that yellow or orange bubble that takes me to the test page

**Comment by alexandruradovici** [comment]
Please make another commit and push it again. Make sure you run git pull before commiting.

**Comment by alexandruradovici** [comment]
Did it work?

**Comment by Edy1504** [comment]
Yes

vin., 29 mar. 2024, 17:07 Alexandru Radovici ***@***.***> a
scris:
