### ISSUE TITLE
I have an error when I've tried to start a session on VB.I've tried on 3 diffrent verssions of VB.

### ISSUE THREAD

**Issue by Elena2109** [UPB-FILS-SdE2/questions#11]
![WhatsApp Image 2021-03-11 at 19 26 34](https://user-images.githubusercontent.com/68807265/110828841-2447de00-82a0-11eb-9deb-f75311f4b7d9.jpeg)

**Comment by sudo-art** [comment]
Make sure Network Adapters 2,3 & 4 are disabled

**Comment by Elena2109** [comment]
Thank you so much!Now it works.
