### ISSUE TITLE
[filesystem] Vague command requirement

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-SdE2/questions#110]
The `open` command goes as follows "Cette fonction d'ouvrir un fichier en **mode lecteure seule**" which translated means that the file is to be opened in read-only mode (correct me if I'm wrong here).
However, the signature of the corresponding command function expects a `PermissionMode` argument to be passed to it.

Questions:
1. Is this discrepancy between the command requirement and the function signature intended?
2. Which has higher precedence: the command requirement or the signature of the supplied function? (this is so I can default to one of the 2 in case a similar issue arises)

**Comment by alexandruradovici** [comment]
It is a mistake, the `open` function opens a file with the requested permissions. Please send us a pull request.

**Comment by popescuatopg** [comment]
Created PR in [upb-fils-sde2.github.io](https://github.com/UPB-FILS-SdE2/upb-fils-sde2.github.io/pull/36). Once the changes are merged, I'll proceed to close this PR.

**Comment by alexandruradovici** [comment]
Thank you, the homework should be updated.
