### ISSUE TITLE
[filesystem] Error handling in the `read` command

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-SdE2/questions#111]
The `read` command is documented as either returning the number of read bytes or a `FileSystemError`. However, writing to the passed buffer may result in an error that is not a `FileSystemError`.

Is `panic!()`-king ok in this case (and other similar cases throughout the homework), should there be another FileSystemError enum option specific for this, or is there another way we should tackle it?

**Comment by alexandruradovici** [comment]
I don't think you can get an error while writing to the provided slice/buffer? What error do you have in mind?

**Comment by popescuatopg** [comment]
Had a general IO Error in mind but you are right since we are not reading from an actual file.
