### ISSUE TITLE
[filesystem] Clarify `create` command requirement

### ISSUE THREAD

**Issue by popescuatopg** [UPB-FILS-SdE2/questions#112]
The `create` command is documented as opening a file (and creating it if it doesn't exist) with read-only permissions, while also taking a `PermissionsMode` argument.
Does the function's signature take precedence over the command's requirement in this case, or not?

**Comment by alexandruradovici** [comment]
The `PermissionsMode` parameter defines the file's permissions, not the opening permissions.

**Comment by popescuatopg** [comment]
Much thanks, that clarified it for me.
