### ISSUE TITLE
[filesystem] git merge is buggy / how do we hard reset?

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-SdE2/questions#114]
After your message yesterday "General Veuillez mettre à jour le repository de devoir de système de fichiers car nous avons corrigé une erreur dans le template." I tried fetching and merging the changes but I kept getting the message "Already up to date" when the read was still missing the &mut, thus the code still buggy. 

I then tried every possible variation of git merge/pull/fetch but that still didn't work so I had to fix the code manually. 
 
How can this be avoided and please how do we forcefully delete/hard reset the repository so we can start over if something like this happens and we can't fix it?

**Comment by OmarMDev** [comment]
![image](https://github.com/UPB-FILS-SdE2/questions/assets/162307601/559c7fe2-6e2a-4986-8c95-62053ce234cc)
Now this keeps happening. As we don't have the necessary permissions, please can you reset my repo? thank you

**Comment by alexandruradovici** [comment]
The error seems to be form codespace, not from the repository. You can update you repo from the GitHub (not codespace) UI, by selecting the *Sync Fork*.

If codespace is not working:
  - install Rust on your computer (https://www.rust-lang.org/)
  - imstall GitHub Desktop (https://desktop.github.com/)
  - clone the repository and work locally
![Screenshot 2024-04-04 at 18 07 37](https://github.com/UPB-FILS-SdE2/questions/assets/2838177/19e24719-d59f-45a7-99b6-262a5f22832b)

**Comment by OmarMDev** [comment]
![image](https://github.com/UPB-FILS-SdE2/questions/assets/162307601/795a2ce0-f7db-4dc1-9f2f-78bcda0cd068)
![image](https://github.com/UPB-FILS-SdE2/questions/assets/162307601/84ef6157-02e5-4410-9086-ed496951b519)
Here are screenshots from GitHub's GUI (outside codespace) As you can see, the file still contains the wrong code, even though the commit is visible in the history (which is blowing my mind I have no idea how this is possible)

**Comment by alexandruradovici** [comment]
It is the correct file, just that you have to modify the trait `FileSystem` in your implementation (in the `sde2_fs`) crate. From what I see, your repository is correct now.
