### ISSUE TITLE
[filesystem] immutable data vector in inodes

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-SdE2/questions#116]
In order to actually be able to write into the INodes, shouldn't the data vector be mutable?

**Comment by alexandruradovici** [comment]
Are you referring to the `write` function?

**Comment by OmarMDev** [comment]
Referring to the INode Enum, specifically INode::File

Currently, the way it is structured, the data vector is immutable.

This is a problem, in the context of the write function, because of the
following reason:

While we can simply replace the INode inside the fd, and pass some tests
(which is what I've done), other tests explicitly open the file again and
check it's contents from a new fd, meaning the INode has to be modified.

In order to pass those tests, we really should be allowed to make the data
vector in the file INode mutable, no?

**Comment by alexandruradovici** [comment]
The elements of an `enum` cannot be mutable or immutable. The `FileSysyem`'s trait functions take `&mut self` and this allows you to mutate your structure.

**Comment by alexandruradovici** [comment]
Your are not allowed to keep the `INode` in an fd. You have to have a tree structure for your file sustem, the fd just points to one of them (most probably by keeping the file's full name).
