### ISSUE TITLE
[Scheduler] error occurring in a file we're not allowed to touch

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-SdE2/questions#118]
![image](https://github.com/UPB-FILS-SdE2/questions/assets/162307601/01ee842c-c428-4080-b64a-b033386309a2)
As you can see when trying to run tests, it panics because of an unwrap that is in the scheduler/src/scheduler.rs file, we we don't touch. 

No idea why this happens but obviously it's not related to the files I wrote/made so please can you help? Thank you!

**Comment by alexandruradovici** [comment]
Please look that line, it transforms a `usize​` into a `NonZeroUsize`. This has one number for whici it fails, 0.

You are trying to make a pid with a value 0.

**Comment by OmarMDev** [comment]
That is very helpful, thank you!
