### ISSUE TITLE
[Rustyloader] cargo issue, individual tests

### ISSUE THREAD

**Issue by OmarMDev** [UPB-FILS-SdE2/questions#120]
When cloning into the devoir-4-tests repo, and trying to set it up I run into a few issues. 

1. Any time I try to run a cargo command, I get "bash: cargo: command not found" regardless of where I am in the directory. 
2. In the setup process, when running the "make" command in devoir-4-tests/inputs, I get the following error: 

"In file included from /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9,
                 from check_perm.c:1:
/usr/include/stdint.h:26:10: fatal error: bits/libc-header-start.h: No such file or directory
   26 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated."

after this, anytime I try running commands for any of the tests I'm unable to. 

Is running individual tests for this homework allowed, and if so, please could you show us how? 

Thank you in advance!

**Comment by alexandruradovici** [comment]
You cannot run the tests like that, please look into the `.gtihub` folder to see what command the grader runs.
