### ISSUE TITLE
Wrong tests for qsort and hello. 

### ISSUE THREAD

**Issue by victorlisman** [UPB-FILS-SdE2/questions#123]
The mapping for the segments for qsort work just fine, even though it segfaults at the end(when jumping to the base_adress,, tried debugging with gdb, it maps just fine just segfaults). Picture for reference:
![image](https://github.com/UPB-FILS-SdE2/questions/assets/62936850/cf4b378a-9ce2-43a2-a41d-08c6f8bf8789)
For hello, the output is the same length, as it should be, it maps just fine, and exits with the correct code. For some reason it does not print the characters and instead fills it with NULL. Pics for refrence:
![image](https://github.com/UPB-FILS-SdE2/questions/assets/62936850/f33b7b78-8386-4511-b5e2-97fe39a43b11)
![image](https://github.com/UPB-FILS-SdE2/questions/assets/62936850/303deebd-1835-4eaf-ad3d-7b58fd81f94e)
![image](https://github.com/UPB-FILS-SdE2/questions/assets/62936850/5ca287c2-b4d4-4eb5-8916-a9cbf4176245)

**Comment by alexandruradovici** [comment]
Did you map the correct data section in the memory? Bss and data may be in the same page, in this case it means rthat you have to zero out the bss part yourself.

**Comment by victorlisman** [comment]
Hmmmm, it seems to have fixed the issue for the hello output, but here is something I am really confused about. If I transmute the entry point into an anonymous function at the end of executing, hello outputs correctly, but qsort segfault by going into kernel space??????. If i don't transmute at the end, both qsort and hello return the correct codes(0) and map correctly, but they don't output anything.

**Comment by alexandruradovici** [comment]
What dors transmute the entry point mean?

**Comment by victorlisman** [comment]
I call `std::mem::transmute` on the entry point and allocate as a const  fn pointer to an extern C fn, and then subsequently call that fn. This is wrapped into an unsafe block.(I do this at the end of the exec fn) For some reason this makes hello work correctly, but segfaults qsort. If I comment it out, both qsort and hello map and return correctly, but output nothing.

**Comment by alexandruradovici** [comment]
You should never do that, starting the elf is not just that. We have the `runner` module for that.

**Comment by victorlisman** [comment]
I know, I just wanted to know why hello only outputed when i did that

**Comment by alexandruradovici** [comment]
The elf loader does not directly call your entry point, it has to set up the arguments and the environment variables.
