### ISSUE TITLE
i have some problems to rezolv this part ,can you hep me with some ideas ?

### ISSUE THREAD

**Issue by Andersonkouassi91** [UPB-FILS-SdE2/questions#13]
![image](https://user-images.githubusercontent.com/79939646/111039484-f9dc5900-8436-11eb-92fb-baa1e0c8a4aa.png)

**Comment by valexandru** [comment]
The reason why what you are trying is not working is that you are not escaping all characters, especially the last one: ' . A hint would be to search for how to escape characters in bash.
