### ISSUE TITLE
Checker returns different results depending on where it's run

### ISSUE THREAD

**Issue by PoseaC** [UPB-FILS-SdE2/questions#14]
![image](https://user-images.githubusercontent.com/77210590/111080782-ab978a80-8508-11eb-86a0-9f4a85178d2d.png)
I was doing some last minute tests before submitting the homework and I found out that depending on what folder I'm in when I run the checker I get different results, if I run it from the tema2-scripts or the tema2-scripts-output folder it says that everything is alright and I get 100 points, but if I run it from the /home/student folder it says that the last 2 two tasks are incorrect and I get only 57 points, what could cause this?

**Comment by ioanaculic** [comment]
I believe the problem is that you use relative paths in your scripts.
