### ISSUE TITLE
Devoir sde <demande d’explication >

### ISSUE THREAD

**Issue by rania-slimani** [UPB-FILS-SdE2/questions#16]
Bonjour monsieur / madame 
Serait il possible svp de me dire si si le fichier SQL$lammer est juste un fichier et c est juste son nom 'SQL $lammer' ou y a un autre truc et la même chose pour mailto:`netwalker' est ce que c est juste un fichier avec ce nom ou on a autre chose à faire ?! 
merci bcp

**Comment by ioanaculic** [comment]
c'est un simple fichier qui a le nom 'SQL $lammer'
