### ISSUE TITLE
Devoir 1- Task 6

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#17]
What does it mean in the task explanation when it says "Servici aferente/Related Service"? 
Wich parameter from the /etc/passwd file is a related service?
![huh](https://user-images.githubusercontent.com/79825137/111520189-88ffae80-8760-11eb-840a-97c680ad044b.png)

**Comment by ioanaculic** [comment]
The service is the 5th column.
