### ISSUE TITLE
Task 05 issue: A file was not moved correctly

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-SdE2/questions#18]
In task 5, after I execute the oneliner and copy the files from Malware to Clone the checker gives me this error (at line 3):
![2021-03-17 (4)](https://user-images.githubusercontent.com/63002082/111542459-6e3a3380-877a-11eb-8b35-15693ace21ae.png)
When I look inside the Clone folder to see if the Mailto: `Netwalker' file is at the place it should be, I find it there. What can trigger this error?

**Comment by ioanaculic** [comment]
As the checker states, you need to move the file, not copy it.

**Comment by Cristiana959** [comment]
Thank you, it works now. I thought that the checker gave this error because there was a problem with the first part of this task
 (copying Malware to Clone).
