### ISSUE TITLE
Serait-il possible de faire des changements

### ISSUE THREAD

**Issue by rania-slimani** [UPB-FILS-SdE2/questions#19]
Bonjour
 je voulais savoir si c'est possible étant donné qu'on a pas encore dépassé la date limite pour soumettre les devoirs de modifier ce que j ai fais  car malheureusement j'ai mit un "submit" sans faire un "check" 
Ou y aura quand même une vérification manuelle pour voir que y a des trucs qui marchent bien afin de ne pas tout perdre

**Comment by ioanaculic** [comment]
You can run submit anytime. Only the last submit will be taken into account.
