### ISSUE TITLE
Devoir 1 - Where do i check if my homework was submitted?

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#20]
Where do i check if my homework was submitted corectly?
And if i submitted the homework can i submitt it again in the case of finishing another task?

**Comment by ioanaculic** [comment]
You can check the submission on the web platform where you logged in to start solving the homework (temeuso.cs.pub.ro).
Yes, you can submit the homework several times, the last sub mission will be taken into account.
