### ISSUE TITLE
Eroare Task06 Tema 1

### ISSUE THREAD

**Issue by RalucaCraciun** [UPB-FILS-SdE2/questions#21]
Am incercat sa schimb permisiunile fisierului /etc/passwd cu sudo chmod (crezand ca acesta e fisierul caruia trebuia sa i schimb permisiunile, dar mi am dat seama ca  a fost o prostie) dupa care, cand am incercat sa rulez comanda sudo uso check mi a aparut eroarea "sudo: unknown uid 1000: who are you?", iar cand am incercat  sa ma loghez din nou ca student se afiseaza "su: Cannot determine your user name".  Ma puteti ajuta sa rezolv aceasta problema, va rog?

**Comment by ioanaculic** [comment]
Din pacate singura solutie e sa descarci din nou masina virtuala si sa iei tema de la 0.

**Comment by RalucaCraciun** [comment]
Am inteles, multumesc mult!
