### ISSUE TITLE
[Devoir 2 - Micro:bit Busybox] Celsius to Kelvin formula

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-SdE2/questions#26]
Hello! What formula should we use to convert the temperature from Celsius to Kelvin? The same one from physics?

**Comment by alexandruradovici** [comment]
That is the only formula that exists 😄

**Comment by Cristiana959** [comment]
Ah ok :). I didn't know if we should use 273,15 or if we should approximate with 273.

**Comment by ioanaculic** [comment]
273,15 :)
