### ISSUE TITLE
[Devoir 2 - Micro:bit Busybox] Tests led/on_off and led/mixed might have an incorrect output

### ISSUE THREAD

**Issue by Cristiana959** [UPB-FILS-SdE2/questions#27]
As I was checking my code I noticed that the output for the tests led/on_off and led/mixed might be incorrect. When the "led 0 0 off" is executed the corresponding output is "Set pixel 0 0 to 9", when I think that it should have been "Set pixel 0 0 to 0", because we are switching off the led. Here is my output compared to the desired output:

led/on_off

![2021-03-30 (4)](https://user-images.githubusercontent.com/63002082/113019326-252aac00-918a-11eb-8f52-6e1208be50eb.png)

led/mixed

![2021-03-30 (5)](https://user-images.githubusercontent.com/63002082/113019396-3d023000-918a-11eb-94fd-7e57d8bdd585.png)

**Comment by ioanaculic** [comment]
Indeed there was a problem with those two tests, thank you for signaling it. 
Now it should be fixed. Please push another commit and the tests will be run again.
