### ISSUE TITLE
Small issue in behaviour

### ISSUE THREAD

**Issue by AndreiCristianMoga** [UPB-FILS-SdE2/questions#28]
Hi. I did my assignment and submitted it. One thing i do not understand: when the checker runs the tests, it almost completely checks out, but out of nowhere it drops a "None" into the output. I did not write anywhere print("None"), yet that line appears and fails an otherwise good check
![error_wth](https://user-images.githubusercontent.com/79591367/113270601-54ecc780-92e2-11eb-8eb5-8e34ef6c82cc.JPG)
![error_wth_again](https://user-images.githubusercontent.com/79591367/113270600-54ecc780-92e2-11eb-8a79-cd574f5d22b7.JPG)
I don't understand why this happens. Please, help me?

**Comment by ioanaculic** [comment]
That means that you are trying to print a value that does not exist, most probably an uninitialized variable or the return value of a function that actually does not return anything.

**Comment by AndreiCristianMoga** [comment]
Thank you, all done. Works like a treat
