### ISSUE TITLE
Devoir 2  "error_simple_1.in" Incorect test?

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#29]
![invalid led](https://user-images.githubusercontent.com/79825137/113477848-9ec5e100-948d-11eb-8314-b17cf7fe22f3.png)
Shouldn't here be invalid led?

**Comment by DamarisParciu** [comment]
If I may add, in error_simple_2.in the command is "led blink 500 0 0" and in error_simple_2.out is only "Invalid count." 
Shouldn't there be both "Invalid count." and "Invalid LED." ?

**Comment by GheorgheTeodorFlorian** [comment]
> If I may add, in error_simple_2.in the command is "led blink 500 0 0" and in error_simple_2.out is only "Invalid count."
> Shouldn't there be both "Invalid count." and "Invalid LED." ?

No, its "led blink interval count x y" so the correct output is "Invalid count value."
Our leds are between 0 and 4 for both x and y the position 0 0 is valid the count is between 0 and 20 so count 30 is invalid.
![probs](https://user-images.githubusercontent.com/79825137/113505940-7fd95480-954a-11eb-92c4-7123161774eb.png)

**Comment by ioanaculic** [comment]
Indeed, for error_simple_1 there is a mistake with the test. Invalid LED should be the error. I am changing it now and please try to rerun the tests.

**Comment by GheorgheTeodorFlorian** [comment]
> Indeed, for error_simple_1 there is a mistake with the test. Invalid LED should be the error. I am changing it now and please try to rerun the tests.

The github autograding didnt receive the update but outside that it runs fine on my local machine.
Thanks for the help.
