### ISSUE TITLE
Autograding issue

### ISSUE THREAD

**Issue by biancaparaschiv** [UPB-FILS-SdE2/questions#30]
The Autograding system doesn't score anything for me, even though I have the same Output. Can you check what the problem is please?
![Capture](https://user-images.githubusercontent.com/79789661/113478956-b2c11100-9494-11eb-8a6d-0a67e5c6eb82.PNG)

**Comment by DamarisParciu** [comment]
I believe that there is an issue in your code: in the correct output the first line always starts with "cmd: ", while your output doesn't.

**Comment by biancaparaschiv** [comment]
You're right that was the problem, thank you.
