### ISSUE TITLE
[busybox] Issues with the outputs for led/brightness_1 and led/mixed tests

### ISSUE THREAD

**Issue by sofialospa** [UPB-FILS-SdE2/questions#32]
I think there's a problem with the brightness_1 and mixed outputs. There are no commands in the input files that correspond with 
the values "2" (in brightness_1.out) and "4" (in mixed.out) :

brightness_1.out
![Screenshot from 2021-04-04 21-09-22](https://user-images.githubusercontent.com/39867824/113517700-49bbc500-958a-11eb-9f94-5a6fb332c26e.png)

mixed.out
![Screenshot from 2021-04-04 21-11-55](https://user-images.githubusercontent.com/39867824/113517720-6f48ce80-958a-11eb-974a-3f2bdaa2a816.png)

**Comment by ioanaculic** [comment]
It is the value printed by the brightness set command.

**Comment by sofialospa** [comment]
I didn't notice. It works. Thank you:)
