### ISSUE TITLE
Difference between tests for blink

### ISSUE THREAD

**Issue by ghost** [UPB-FILS-SdE2/questions#33]
Hello! I'm sorry to bother you, but i may have found a discrepancy between the outputs of two test files for the same test. For the blink test, the sleep duration between turning on the led and turning it off is 500ms, while in the mixed test, at the blink part, the same duration is 100ms, thus either one or the other test is failing. Or maybe i did something wrong, in which case, I'm sorry!
![blink](https://user-images.githubusercontent.com/79828089/113609607-aa173900-9654-11eb-91d0-ab9881e71fe9.png)
![mixed](https://user-images.githubusercontent.com/79828089/113609610-aaafcf80-9654-11eb-9e80-63522a5d388c.png)

**Comment by ioanaculic** [comment]
The sleep duration is a parameter passed to led blink, so it can vary throughout the tests.

**Comment by ghost** [comment]
Ah so thats there too, i thought the sleep parameter is just for between an led cycle (the led turning on-turning off). Got it, thank you! :D
