### ISSUE TITLE
Question about ls

### ISSUE THREAD

**Issue by ghost** [UPB-FILS-SdE2/questions#35]
Hello! I have a small question a part in ls:
![Screenshot 2021-04-06 121554](https://user-images.githubusercontent.com/79828089/113688476-02405080-96d2-11eb-9f9b-0ee275271778.png)
Does this mean that we must display the filename only? Or do we have to display its size also, regardless of the existence of the -l/--long parameter?

**Comment by ioanaculic** [comment]
That depends on how the command is used. If it is used with the -l/--long option, you also need to display the size, if not, you don't display the size.

**Comment by ghost** [comment]
And if we dont have the ls in a function, do we have to do the "returns -80 in case of error" part too? Do we necessarily have to put ls in a function to be able to return?

**Comment by ioanaculic** [comment]
No, you don't have to do that. That line was trailing there, our mistake :)
We removed that line from the homework (please refresh in the browser), so you don't have to bother with return values.

**Comment by ghost** [comment]
Alright, thank you very much!
