### ISSUE TITLE
Round Robin test issue

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#38]
![issue](https://user-images.githubusercontent.com/79825137/115117643-512a9780-9fa8-11eb-8575-74e0c8890eeb.png)
In three-worker-sleeper (round robin) after process 1 is executed in the highlighted area shouldn't process 2 be next?
Process 3 was already executed previously.

**Comment by ioanaculic** [comment]
When process 3 is preempted it is automatically put to the back of the queue. After this, the scheduler checks for sleeping processes that need to be put back in queue, resulting in process 2 to be put at the end of the queue, after process 3.

Hope this is clear, your solution could also be correct, it all depends on the checks that the scheduler does, and in this case it works like I described above.

**Comment by GheorgheTeodorFlorian** [comment]
Thanks, i understood .
