### ISSUE TITLE
[scheduler] Round Robin with priorities,test three_workers

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#39]
![problem](https://user-images.githubusercontent.com/79825137/115682361-10db6880-a35e-11eb-90c0-9b9f4cbe82f1.png)
In the three_worker test for rrp, after a period in wich the processes are scheduled in order(2,3,4,2,3,4,......) there is a portion in wich
they are scheduled twice. Why is that?

**Comment by ioanaculic** [comment]
When a process is preempted and has 0 units its behaviour is considered ok and is not downgraded. This is what happens here.
