### ISSUE TITLE
Sudo uso start 0 is not correct, but it works with sudo uso start 1

### ISSUE THREAD

**Issue by SheepSeb** [UPB-FILS-SdE2/questions#4]
It says here to start working on the homework to run "sudo uso start 0", but the homework starts with "sudo uso start 1". It should be changed on the website.

Sudo uso start 0 it starts the homework from the USO Course

![image](https://user-images.githubusercontent.com/19248295/110452357-c6fc3300-80cd-11eb-83b9-f30291f8371d.png)

**Comment by valexandru** [comment]
Yes. We changed it now on ocw to be "sudo uso start 1".
