### ISSUE TITLE
[question] Child process initial virtual runtime 

### ISSUE THREAD

**Issue by irina-b-dev** [UPB-FILS-SdE2/questions#41]
Why is the virtual runtime of the child process (after fork) equal to the parent's vruntime in : 2-workers.pse.cfs.debug,
but 0 in : 3-sleepers.pse.cfs.debug?

![child_vrt_2-workers-pse-cfs-debug](https://user-images.githubusercontent.com/72762129/115923631-30ba7b80-a487-11eb-91a8-91daf4ff1b8c.png)
![child_vrt_3-sleepers-pse-cfs-debug](https://user-images.githubusercontent.com/72762129/115923655-3912b680-a487-11eb-9873-dbfb69004398.png)

**Comment by ioanaculic** [comment]
The virtual runtime at fork is the minimum virtual time in the system. It does not depend on the parent process. As sleeping processes never execute, they always have virtual runtime 0.

**Comment by irina-b-dev** [comment]
Ok. thank you. I didn't take sleeping processes into consideration, initially.
