### ISSUE TITLE
[alarm] Running in parallel 

### ISSUE THREAD

**Issue by GheorgheTeodorFlorian** [UPB-FILS-SdE2/questions#43]
What library or mechanism can i use to run things in parallel for the microbit.
For example i need to wait to get input from the user while i also have to check if buttons are pressed and check the alarm.

**Comment by alexandruradovici** [comment]
You cannot run things in parallel. Using input is not so simple here.

You can use the UART library https://microbit-micropython.readthedocs.io/en/v2-docs/uart.html to verify if there is any input from the user and read it.

**Comment by ioanaculic** [comment]
Indeed, this is a problem. I will clarify the request: the console is activated by pressing any key. Once you press a button, the prompts shows up and you can read commnds. While in this mode, the alarm does not have to work. To deactivate the console, use the command exit.
