### ISSUE TITLE
[alarm] Question about the input demand

### ISSUE THREAD

**Issue by ghost** [UPB-FILS-SdE2/questions#45]
Hello! In the "Configuring the system" category in the homework, what does "To initiate the connection with the terminal, pressing any key suffices" the key part refer to? Pressing any key on the computer in the online Python editor/Mu Editor console, or pressing one of the AB buttons on the microbit microcontroller?
Thank you very much and sorry for the disturbance! :)

**Comment by GheorgheTeodorFlorian** [comment]
> Hello! In the "Configuring the system" category in the homework, what does "To initiate the connection with the terminal, pressing any key suffices" the key part refer to? Pressing any key on the computer in the online Python editor/Mu Editor console, or pressing one of the AB buttons on the microbit microcontroller?
> Thank you very much and sorry for the disturbance! :)

Hello, it refers to pressing any key on the keyboard to start the input terminal.
The terminal being the same one in the code editor besically you cant give it any input until you trigger it with a key press.
Hint: https://microbit-micropython.readthedocs.io/en/v1.0.1/uart.html 
Good luck.

**Comment by ghost** [comment]
Alright, i got it. Thank you very much! :D
