### ISSUE TITLE
[dashboard] Problem with the main program

### ISSUE THREAD

**Issue by ghost** [UPB-FILS-SdE2/questions#47]
@ioanaculic Hello! First I tried to get, using serial, and print in the terminal window the temperature and light values that are sent from the microbit through UART to the PC, but instead of seeing the values, I get nothing displayed. It seems like the program doesn't enter the while loop and I don't know what to do. The microbit program seems to be working fine since the yellow LED on the board blinks every 30s, so i assume that the values are, in fact, sent to the computer, but the computer program locks up somewhere. Could you help me, please? Thank you!

**Comment by ioanaculic** [comment]
Try adding \n to the sent line. This will clear the buffer and make sure the value is sent.

**Comment by ghost** [comment]
Now i have some output, but not what i expected:
![Screenshot 2021-06-08 173139](https://user-images.githubusercontent.com/79828089/121204374-86a08280-c87f-11eb-93a3-03f7bd69013e.png)
EDIT: I solved using the decode line that you put in the UART TP meeting chat on Teams. Thank you! :)
