### ISSUE TITLE
[devoir 0] All checks have failed

### ISSUE THREAD

**Issue by Liza-Batache** [UPB-FILS-SdE2/questions#49]
Hello, what does this mean? Please advise, thanks
Whenever i check the details, i find : ❌ Run ::error::The output for test Run did not match%0AExpected:%0AOK%0AActual:%0AOk
![image](https://user-images.githubusercontent.com/101167550/158035614-b80ef930-f612-45a0-ae60-68ced5526b8b.png)

**Comment by alexandruradovici** [comment]
Please click on details and you will see the error.

EDIT: check your spelling, the text you wrote does not match the expected text.

**Comment by Liza-Batache** [comment]
Solved; thank you
