### ISSUE TITLE
SSH connexion doesn't work...

### ISSUE THREAD

**Issue by sudo-art** [UPB-FILS-SdE2/questions#5]
Hello !

Unfortunately, when I'm trying to connect via SSH, I am always displayed 'Access denied' regardless the method I choose. Below, a photo is attached to see what I am talking about ...

![1234](https://user-images.githubusercontent.com/61539411/110601661-dd69c380-818d-11eb-9565-db1115002bff.png)

**Comment by valexandru** [comment]
From what i can see you are using PuTTY, what parameters are you passing for ssh (meaning hostname/IP address and port)?

**Comment by sudo-art** [comment]
localhost port: 2222
 
I am using VirtualBox as the instructions mention

**Comment by valexandru** [comment]
Hmm... Do you have internet connection in the virtual machine? (Try running: ping 8.8.8.8 and tell me the output). If you do have internet, try running "ip adress show" in the virtual machine. Then, use that ip address instead of localhost and then port 22 instead of 2222 and tell me if it works.

**Comment by sudo-art** [comment]
I have internet connection for sure. I have tried to use the other method but in vain (Timed out message)

**Comment by sudo-art** [comment]
I thought that I should generate a key to connect the two virtual machines , which I did but again in vain. I got the same message

**Comment by valexandru** [comment]
So what does "ping 8.8.8.8" return in the virtual machine?

**Comment by sudo-art** [comment]
Lots of replies

**Comment by alexandruradovici** [comment]
Can you check the network settings of the virtual machine, section Port Forwarding? Does it have a ssh rule?

**Comment by sudo-art** [comment]
![2345](https://user-images.githubusercontent.com/61539411/110662294-08740780-81ce-11eb-870b-01573b6ec3d8.png)

**Comment by sudo-art** [comment]
I have renamed 'Rule 1' to be SSH. It doesn't work that way either

**Comment by sudo-art** [comment]
Is everything all right if I try to disable the firewall of the virtual machine ? I know we have been informed not to play with the vm's settings.  Otherwise, we will receive 0 points. But I'm thinking of this hindrance, maybe this way I can solve it. That's why I'm asking...

**Comment by sudo-art** [comment]
> Is everything all right if I try to disable the firewall of the virtual machine ? I know we have been informed not to play with the vm's settings. Otherwise, we will receive 0 points. But I'm thinking of this hindrance, maybe this way I can solve it. That's why I'm asking...

Unfortunately, disabling the firewall on both the host and the vm is not a solution

**Comment by sudo-art** [comment]
> > Is everything all right if I try to disable the firewall of the virtual machine ? I know we have been informed not to play with the vm's settings. Otherwise, we will receive 0 points. But I'm thinking of this hindrance, maybe this way I can solve it. That's why I'm asking...
> 
> Unfortunately, disabling the firewall on both the host and the vm is not a solution

For all those who have encountered the same problem, know that not disabling the firewalls is as important as the fact that you need to make sure that you have configured the port to listen on 22 or you have not commented the respective code line in the sshd_config file.
