### ISSUE TITLE
[devoir1]Code working on the local machine but not on workflow

### ISSUE THREAD

**Issue by elalae** [UPB-FILS-SdE2/questions#50]
My function works well on my local machine, but the Autograding keeps on showing these errors. What could be the issue here?
![image](https://user-images.githubusercontent.com/33804236/160105787-3259adf6-3a4f-4921-a8e3-64c40533ce39.png)
![image](https://user-images.githubusercontent.com/33804236/160105935-78f67688-de19-4bfa-be33-b41be052f4a3.png)
![image](https://user-images.githubusercontent.com/33804236/160106025-823e3299-ca0b-4e26-96cd-f33b8856a56c.png)

**Comment by alexandruradovici** [comment]
Look at the Output and Hints part. For cat, it seems that you have an extra empty line. Most probably you are using println! addding an empty newline at the end. Try using print! to avoid the newline.
