### ISSUE TITLE
[rustybox] grep regex

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#51]
For the grep command, how can I import the regex library without using cargo, since we need to add a dependency in cargo.toml to use the regex crate?

**Comment by alexandruradovici** [comment]
You are right,you have to use the regexor a similar library. 

Add it by using cargo add regex.

**Comment by TeodoraMiu** [comment]
My project isn't a cargo project, since in the examples ./rustybox was used to run the project instead of cargo run rustybox.rs. Do I have to make it a cargo project in order to use cargo add regex?

**Comment by alexandruradovici** [comment]
All projects are managed by cargo. If you have the cargo.toml file you can use cargo.

Our tester runs cargo install --path . to add your project to the PATH variable so that it can be run directly as rustybox.

**Comment by TeodoraMiu** [comment]
so i must treat the command line as "cargo run rustybox.rs ..."? or as "./rustybox ..."? (when extracting the command line parameters, because the positions in the array will change)

**Comment by alexandruradovici** [comment]
Both are the same, cargo run simulates the direct usage of rustybox.
