### ISSUE TITLE
[rustybox]<Cannot clone project>

### ISSUE THREAD

**Issue by CAmi307** [UPB-FILS-SdE2/questions#52]
I've tried to clone the project using the command "git clone link" in ubuntu and I get this error: 
![Screenshot (777)](https://user-images.githubusercontent.com/101173949/160152668-554406b8-6b5b-45d5-a723-5f445ce22b46.png)

**Comment by alexandruradovici** [comment]
You have to create a github personal access token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token and use it as the password.
