### ISSUE TITLE
[rustybox] error handling

### ISSUE THREAD

**Issue by vladgabrielneculai** [UPB-FILS-SdE2/questions#56]
How can I apply std::process::exit(code) when I am not using match syntax?

**Comment by CAmi307** [comment]
I didn't understand either how should I be handling the errors. Where in the code, how..

**Comment by alexandruradovici** [comment]
The std::process::exit function is a simple function call, it does not depend on match. If you want to exit with an error, just call this function.

**Comment by alexandruradovici** [comment]
> I didn't understand either how should I be handling the errors. Where in the code, how..

You have to exit with a specific error whenever something is not working as expected. For instance for `cat`, if you cannot read a file, you exit with -20.

EDIT: -20 is an signed value, the shell will most probably display the unsigned interpretation of it

```rust
let exit_value: i8 = -20;
println!("signed {}, unsigned {}", exit_value, exit_value as u8);
```
