### ISSUE TITLE
[rustybox] ls -l

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#57]
Is there any function we can use to show all information on a file for the ls -l command? Or must we print permissions, properties, user, group etc by hand? If so, how do we make the permissions have the rwx representation, instead of the octal one?

**Comment by alexandruradovici** [comment]
No there is not. You have to manually print them. These permissions can be retrieved using the `mode` property. This is an u32 that represents all the permissions. Print the `mode` value in binary (`println!("{:b}", mode);`) and take a look at the bits.

Use shift (`n>>0`, `n>>3` and `n>>6`) and masks (`n & 0b111`) to take out only the bits that you need.

To verify if a certain bit is set, you can use:
```rust
let mode = ...
// verify bin n
if mode & (1<<n) != 0 {
  // bit n is set
}

if (mode >> n) & 0b1 != 0 {
  // bit n is set
}
```

**Comment by alexandruradovici** [comment]
You can take a look at the [solutions](https://github.com/UPB-FILS-SdE2/Solutions/tree/main/tp3/ex2) for tp3, exercise 2.
