### ISSUE TITLE
[rustybox] ls all prints extra files

### ISSUE THREAD

**Issue by elalae** [UPB-FILS-SdE2/questions#58]
My ls -a/--all commands keeps on returning an error in autograding with the following hint:
![image](https://user-images.githubusercontent.com/33804236/160245285-a58ab49b-4984-4bde-a50b-d81bc54282db.png)
What does it mean? Isn't it supposed to print all files?

**Comment by alexandruradovici** [comment]
Please run the command on your computer and post its output here.

**Comment by elalae** [comment]
> Please run the command on your computer and post its output here.

![image](https://user-images.githubusercontent.com/33804236/160252913-60cf1807-cfa0-4934-99d8-05aad888d0f7.png)

**Comment by alexandruradovici** [comment]
You are printing the full path, you should only print the file name.

**Comment by elalae** [comment]
> You are printing the full path, you should only print the file name.


like this?
![image](https://user-images.githubusercontent.com/33804236/160255443-b3603da6-4434-443a-b17f-72518b2f3978.png)

**Comment by alexandruradovici** [comment]
Yes, but without the quotes. Use {} for print.

**Comment by elalae** [comment]
> Yes, but without the quotes. Use {} for print.

Is this output good?

![image](https://user-images.githubusercontent.com/33804236/160256487-53248ff1-644c-493a-8c34-46eacc2cf46d.png)

**Comment by alexandruradovici** [comment]
This should be fine

**Comment by elalae** [comment]
> This should be fine

Even if the autograding outputs the same error?

![image](https://user-images.githubusercontent.com/33804236/160256929-04010003-577a-4f9b-9cba-745ca09990fa.png)

**Comment by alexandruradovici** [comment]
Try running ls -a on your computer and see what it prints. Look at your output and see what is different.

**Comment by elalae** [comment]
> Try running ls -a on your computer and see what it prints. Look at your output and see what is different.

The files and dirs are the same. Could the links be the issue? :-? 

![image](https://user-images.githubusercontent.com/33804236/160258772-28470382-b20a-4a95-97a2-d977c2cf4d49.png)

**Comment by alexandruradovici** [comment]
Please look carrefully at everything that ls -a prints.
