### ISSUE TITLE
activation code doesn't work

### ISSUE THREAD

**Issue by EvelyneMorariu** [UPB-FILS-SdE2/questions#6]
Every time I try to write manually or by copying the code from the virtual machine, it doesn't work
![Picture1](https://user-images.githubusercontent.com/61755963/110636042-790e2a80-81b4-11eb-890e-708cebd6fd05.png)

**Comment by valexandru** [comment]
You have to login on "https://temeuso.cs.pub.ro" before entering the CLI ID
