### ISSUE TITLE
[rustybox] <rmdir exists error>

### ISSUE THREAD

**Issue by vladgabrielneculai** [UPB-FILS-SdE2/questions#60]
I've finished writing the function for the rmdir command but i have a small problem. All checks worked, but for rmedir exists error did not. How can i solve this problem?
![eroare](https://user-images.githubusercontent.com/81146225/160283496-481ac8d2-4758-4089-94f0-68b8700318c4.png)

**Comment by alexandruradovici** [comment]
Your rustybox seems to panic instead of returning an error code.
