### ISSUE TITLE
[rustybox] Invalid parameters

### ISSUE THREAD

**Issue by elalae** [UPB-FILS-SdE2/questions#61]
What do the invalid parameters/parameters 2 checks do?
![image](https://user-images.githubusercontent.com/33804236/160288101-84674975-8847-4e8e-b196-c0aa33fbaf4f.png)

**Comment by alexandruradovici** [comment]
You can take a look at the test https://github.com/UPB-FILS-SdE2/devoir-1-tests/tree/main/verify/invalid
