### ISSUE TITLE
[rustybox] mv dir

### ISSUE THREAD

**Issue by vladgabrielneculai** [UPB-FILS-SdE2/questions#65]
Hello, I am having a small problem with the test for mv dir. I tried in visual studio using cargo to move my folder and it works, but on GitHub I get this message. How can I solve this? 
![image](https://user-images.githubusercontent.com/81146225/160767202-d733fbe3-2970-4ec1-b7f0-32ec3926e60c.png)

**Comment by alexandruradovici** [comment]
I ran the following commands using your solution:

```bash
rm -rf output/*
rm -rf simpsons

mkdir simpsons
echo "ay caramba" > simpsons/bart
echo "ay caramba" > output/bart
mkdir simpsons/lisa
touch simpsons/lisa/homework
echo "150" > simpsons/lisa/mensa
echo "150" > output/lisa

rustybox mv simpsons "the simpsons"
echo $?
```
The rustybox command works correctly but it returns -40 (216)
