### ISSUE TITLE
[memory game] <Source code upload>

### ISSUE THREAD

**Issue by AmirAlSakban** [UPB-FILS-SdE2/questions#66]
Buna ziua! Am vazut ca trebuie sa convertim din blocks in phyton si apoi sa incarcam pe github. Deci codul in phyton se considera cod sursa sau nu? Si daca da, atunci noi ce mai publicam?

**Comment by Cristiana959** [comment]
Codul de Python este cel care trebuie incarcat pe github. Convertirea se face din editorul MakeCode.
