### ISSUE TITLE
[rustyshell] parser panic?

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#68]
Am incercat sa rulez testul 6-stdout-and-stderr si vad ca parser-ul imi da panic pentru token-ul "("
<img width="511" alt="parse_error" src="https://user-images.githubusercontent.com/96741919/162281607-2045af21-6e53-4323-8ef9-170372b1bedd.PNG">

**Comment by alexandruradovici** [comment]
Please update the parser files from https://github.com/UPB-FILS-SdE2/devoir-2-starter
