### ISSUE TITLE
No internet connection in the VM using VMWare

### ISSUE THREAD

**Issue by ghost** [UPB-FILS-SdE2/questions#7]
Hello! I have a little problem with the homework.
I have the VM installed in VMWare because no VM worked for me in Virtualbox for some reason (miss Culic might be able to confirm as i had the same problem in today's SE lab as well) and while it boots fine, i have a problem with the internet in the VM: there isn't any.
![image](https://user-images.githubusercontent.com/79828089/110672340-35c5b300-81d8-11eb-8c89-b03bf687686f.png)

Could you help me please?
Thank you!

**Comment by sudo-art** [comment]
did you type ping _name_of_a_website_ to see if you have any replies ?

**Comment by ghost** [comment]
i get "Temporary failure in name resolution" when i try ping www.google.com

**Comment by sudo-art** [comment]
Below, on the right part of the footer bar, click on the second icon to check if your connexion to the internet is activated... Maybe your virtual machine is disconnected

**Comment by ghost** [comment]
It shows me that it's connected, yet I still can't ping any websites

**Comment by sudo-art** [comment]
In the case it will be good to bridge your port to a wmware port to get access to the internet

**Comment by ghost** [comment]
Could you tell me how to do that please? I'm kind of a newbie in VMWare

**Comment by sudo-art** [comment]
1. Click on Edit (the head bar) > Virtual Network Editor > Add Network > (Choose) NAT > Apply > Ok
2. VM (the head bar) > Removable Devices > Network Adapter > Settings > Network Adapter > Custom: Specific virtual network > Choose the one which you have created > Ok

Now you should be connected (this is a friendly method)

**Comment by ghost** [comment]
It still doesn't work :(

**Comment by sudo-art** [comment]
Have you selected the desired virtual machine before all those steps ?

Choose **NAT** instead of **Custom...** to see if it works... 

![34567](https://user-images.githubusercontent.com/61539411/110678041-86d8a580-81de-11eb-91b4-ecbf7f54c019.png)

**Comment by ghost** [comment]
I did.

**Comment by ghost** [comment]
Sorry for the delay in response, i tried to get Virtualbox to work instead. Had to disable a bunch of Hyper-V and Windows Sandbox related stuff on my system (which im not really comfortable with) for Virtualbox to work, but now it does and i have internet (i get answers from pinging google.com). Now all i have left is to find out how to change the keyboard layout since i have the french layout on my laptop.
Thank you very much for your help! :D

**Comment by alexandruradovici** [comment]
You may use ssh (putty). This will use your computer's layout instead of the virtual machine's.
