### ISSUE TITLE
[rustyshell] <read_word>

### ISSUE THREAD

**Issue by eandreea22** [UPB-FILS-SdE2/questions#70]
i have trouble writing the part with &&Box and ** from read_word
any suggestions?

**Comment by alexandruradovici** [comment]
The `read_word` function *recomposes* a command or a parameter. The command line has the following format:

command parameter1 parameter2 ....

A command or a parameter is composed out of several words. These can be strings, variables (that have to be replaced with their value), commands ($(command ....)) etc

You can run `cargo doc --open` and look at the `parser`.

An example of a command or parameter composed out of several words is `text${VARIABLE}text2` which will be replaced with a string like `"text"+value_of("VARIABLE")+"text2"`. This is just an example and not Rust code.
