### ISSUE TITLE
[rustyshell] unsupported import 'crate::parser::quotes'

### ISSUE THREAD

**Issue by vladgabrielneculai** [UPB-FILS-SdE2/questions#71]
i am having this issue with the shell.rs file.
![image](https://user-images.githubusercontent.com/81146225/162699647-394b75a0-0449-4b53-893e-e085ee969f29.png)
any suggestions?

**Comment by alexandruradovici** [comment]
Run `cargo build` in the terminal.

**Comment by vladgabrielneculai** [comment]
![err](https://user-images.githubusercontent.com/81146225/162701758-20682f2c-d01c-490e-803c-65f9807407a0.png)

**Comment by alexandruradovici** [comment]
You did not replace `mod.rs`. Your file does not define the quotes module. Add `mod quotes` to `mod.rs`.
