### ISSUE TITLE
[rustyshell] variabile

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#72]
Variabilele trebuie setate in shell, nu? (adica cu env::set_var) Ca m-am uitat la testele cu variabile (din 6-env) si vad ca fisierele printenv si run iau variabilele din bash, nu din shell.

**Comment by alexandruradovici** [comment]
Testele sunt rulate asa:

`VARIABILA=valoare ./printenv`

VARIABLA ia valoarea valoare cat timp ruleaza ./printenv. Practic dupa fork, setezi valoarea variabilelor (set_env sau similar) si folosesti dai exec.

**Comment by TeodoraMiu** [comment]
Pai eu vad ca daca dau set_env in copil, variabilele declarate dispar odata cu terminarea procesului copil, pt ca set_env declara variabilele doar in procesul curent.

**Comment by alexandruradovici** [comment]
Asta se si vrea. Daca procesul copil insa porneste alte procese, acestea raman si pentru acelea.

**Comment by TeodoraMiu** [comment]
multumesc, intelesesem eu ceva gresit
