### ISSUE TITLE
[rustyshell] Intrebare la operatii conditionale

### ISSUE THREAD

**Issue by AlexandraNegoita** [UPB-FILS-SdE2/questions#73]
Nu imi dau seama cum ar trebui tratat cazul in care execvp merge bine si returneaza 0, dar comanda de Linux va da eroare. (De exemplu: execvp cu comanda 'ls ./a', ls nu va gasi directorul si va da eroare, dar execvp functioneaza si returneaza 0). Exista o functie de verificare pentru asta, sau se poate face un match?

**Comment by alexandruradovici** [comment]
Daca comanda exista, execvp nu returneaza, executabilul este inlocuit cu cel dat in execvp. Eroare returnata de comanda va fi primita de waitpid in parinte. Ma uit undeva pe codul tau?
