### ISSUE TITLE
[photo contest] <programming language>

### ISSUE THREAD

**Issue by andreisimion99** [UPB-FILS-SdE2/questions#74]
Which language should we use for this project (Blocks, Python or both)? I'm questioning this because the project instructions say:
"Le devoir doit être implémenté en Blocks. Toute autre implémentation conduira à l'annulation du devoir."
"Pour résoudre le devoir vous devez réaliser un programme un program exécutée dans MakeCode, écrit en Python, pour simuler les comportements décrits."

**Comment by Cristiana959** [comment]
The solution to the homework should be written in Python. I will modify the text right away.

**Comment by edytalpaiute** [comment]
If we started the implementation in Blocks should we switch to Python? I already adapted and modeled my design to Blocks so... it would such a shame to start from scratch.

**Comment by Cristiana959** [comment]
You can convert in Python what you've already written and continue from there.
