### ISSUE TITLE
[rustyloader] linking with cc failed

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#76]
Cand incerc sa compilez programul (chiar si cel neschimbat, clonat direct de pe github), imi da o eroare "linking with cc failed" din rusty-loader.

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m32" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.14o7gltjy2g901nw.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.22hygq7ccvaf1wr.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.27je05c27sy6pv0z.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.2vgvp5kfhpolnh7o.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.344dzr3zpoa42h2l.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.38k3iawcdsd258c1.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.3eh852ob08h5a5gx.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.3udcrn3t0u3c5u3c.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.422e65iua5igp46z.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.45c96v3gscaqiwcu.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.45sauc7w1a7tx20e.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.4s3zo5mvzh8b6lsa.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.hqs2eeuigdjj6p4.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.n48u49t04ogh26u.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.shx4ywib9ffhwpt.rcgu.o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388.2mizvnzmkovc5miy.rcgu.o" "-Wl,--as-needed" "-L" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps" "-L" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/debug/deps" "-L" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/libnix-ecbf287805a62c30.rlib" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/libbitflags-5959f2511fb9dd1f.rlib" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/libmemoffset-46ab8c7f7e9bc36b.rlib" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/libcfg_if-d180ff1f11353fd2.rlib" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/liblibc-044d774bd5171272.rlib" "-Wl,--start-group" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-ec4a4965a0dc83e2.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-cf233144db506dd2.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libminiz_oxide-8438d6bde65fbce1.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libadler-39a55c6d7bd1f773.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libobject-12bb4fbb3f223f4f.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libmemchr-8eeefcbf0239ec8c.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libaddr2line-600dffa988290ee9.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libgimli-12dc49ba835c32ba.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librustc_demangle-f0cb03757ae1c6ac.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_detect-bbcf8b317706b000.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libhashbrown-cd4a038788d3649a.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librustc_std_workspace_alloc-f347f8885971ae08.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-625cfa9a77452675.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcfg_if-8a33fe1984425850.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-3030ebb596c296d3.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-58c6c9a55078f2af.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librustc_std_workspace_core-4b642274f6b98cd8.rlib" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-71d8e01e3308da1c.rlib" "-Wl,--end-group" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-1c84fe4eca49d433.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/teomiu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-o" "/home/teomiu/Documents/SDE/Devoir3/devoir-3---rustyloader-TeodoraMiu/target/i686-unknown-linux-gnu/debug/deps/rusty_loader-35916759be802388" "-Wl,--gc-sections" "-no-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-Wl,-Ttext-segment=0x20000000"
  = note: /usr/bin/ld: cannot find crt1.o: No such file or directory
          /usr/bin/ld: cannot find crti.o: No such file or directory
          collect2: error: ld returned 1 exit status
          

warning: `rusty-loader` (bin "rusty-loader") generated 11 warnings
error: could not compile `rusty-loader` due to previous error; 11 warnings emitted

**Comment by alexandruradovici** [comment]
Have a look at what the tests run, you will find what is missing.
