### ISSUE TITLE
[health monitor] <I'm not sure i understand how the sleep tracker works>

### ISSUE THREAD

**Issue by Liza-Batache** [UPB-FILS-SdE2/questions#78]
So in order to enter the sleep mode the user will need to tilt the plate to the left or to the right, but what do you exactly mean by each inclination corresponds to 30 minutes of sleep, do you mean each one of the left and right inclination? or all the existing inclinations? and I also wanted to confirm if we need to exit the sleep mode once the message "Good morning!" displayed ?
Please advise, Thank you !

**Comment by Cristiana959** [comment]
Each left and right inclination corresponds to 30 minutes of sleep. After the message "Good morning" is displayed, you have to exit sleep mode.
