### ISSUE TITLE
i have some problems with Virtualization BIOS

### ISSUE THREAD

**Issue by Andersonkouassi91** [UPB-FILS-SdE2/questions#8]
Hello Alexandru,escuse me for the inconvenience but i have tried the BIOS virtualization support to enable but i cannot find it,here are the information i have when i follow the BIOS [page[])

![WhatsApp Image 2021-03-11 at 09 37 15](https://user-images.githubusercontent.com/79939646/110763742-e1174c00-825a-11eb-9381-f80a885210ed.jpeg)
![WhatsApp Image 2021-03-11 at 09 37 15 (3)](https://user-images.githubusercontent.com/79939646/110763772-e83e5a00-825a-11eb-8138-e74c2d35a739.jpeg)
![WhatsApp Image 2021-03-11 at 09 37 15 (2)](https://user-images.githubusercontent.com/79939646/110763781-ec6a7780-825a-11eb-9d37-0abda44100ad.jpeg)
![WhatsApp Image 2021-03-11 at 09 37 15 (1)](https://user-images.githubusercontent.com/79939646/110763805-f2605880-825a-11eb-8bbc-4bd382fc63c0.jpeg)

**Comment by alexandruradovici** [comment]
It seems to be enabled. The option is at Advanced and is set to enable.

**Comment by alexandruradovici** [comment]
You can try using the newset version if virtual box or vmware.

**Comment by Andersonkouassi91** [comment]
ok thanks  you !
