### ISSUE TITLE
[rustywebserver] jpg, png, zip

### ISSUE THREAD

**Issue by TeodoraMiu** [UPB-FILS-SdE2/questions#81]
Cum trimitem fisiere de tip jpg, png sau zip?

**Comment by alexandruradovici** [comment]
Deschizi fisierul, citesti cate o bucata din el (&mut [u8]) si o trimiti pe socket. cand in buffer citesti 0 bytes stii ca ai citit tot.

nu e nici o diferenta intre tipurile de fisiere html, text si restul.
