### ISSUE TITLE
[rustybox] Test issue - argument passed

### ISSUE THREAD

**Issue by eandreea22** [UPB-FILS-SdE2/questions#82]
In the rm_multiple_mixed test is an error, argument passed is "--R", not "-R"

![Untitled](https://user-images.githubusercontent.com/71290747/224368687-7518af33-8303-4929-95b1-718f06df87ca.png)

**Comment by alexandruradovici** [comment]
Yes, you are right, this is wrong.

**Comment by alexandruradovici** [comment]
It should be fixed now, please update your copy of the tests repository.
