### ISSUE TITLE
[rustybox] - ls -R issue

### ISSUE THREAD

**Issue by eandreea22** [UPB-FILS-SdE2/questions#83]
I don't know what is the difference between "ls -R lstest" and "cargo run ls -R lstest". Do i need quotation mark?

![image](https://user-images.githubusercontent.com/71290747/224689020-2531dc4b-e627-4fed-b35a-08ef0e646d8d.png)
![image](https://user-images.githubusercontent.com/71290747/224689049-9c47f144-8b12-4cbe-a42b-cf8d48ea0054.png)
![image](https://user-images.githubusercontent.com/71290747/224689060-bc1f4e73-fe1d-4a46-bd43-af1f9b8b0a83.png)

**Comment by alexandruradovici** [comment]
Looking into it.

**Comment by alexandruradovici** [comment]
You are trying to replicate the actual behavior of ls, the homework does not require that.

> Liste le contenu de chaque directoire de l'hiérarchie. Pour les fichiers/directoires qui ne se trouvent pas directement dans le point de lecture, il va afficher le chemin complet, ex: output/test/file.

Your output should be something like:

```
modern family
TVshows
modern family/pritchett
modern family/dunphy
modern family/pritchett/jay
modern family/pritchett/gloria
modern family/pritchett/joe
modern family/dunphy/claire
modern family/dunphy/phil
```
