### ISSUE TITLE
[rustybox] rustybox command

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#84]
J'ai vu que dans les testes, aussi que dans l'example, les commandes commencent avec "rustybox" et pas "cargo run". Est-ce qu'on doit aussi implementer cette fonctionalite?

**Comment by Cristiana959** [comment]
No, you don't have to. When you push your code on GitHub, in the workflow that is triggered automatically, Rust compiles an executable file (in our case named rustybox) based on your main.rs. After that, the cargo install command is executed. This command installs the executable in PATH env variable. It enables the program to be run just by using the name of the executable.

If you look at the logs of the 'Rust' test in the workflow, you'll see exactly what is happening.
