### ISSUE TITLE
[rustybox] tests process

### ISSUE THREAD

**Issue by okko222** [UPB-FILS-SdE2/questions#85]
Can i  check if a specific function  (e.g pwd() function) is working as it should work in devoir-1-tests repository ? if the answer was yes please describe the process step by step.

**Comment by alexandruradovici** [comment]
You can upload the homework and it will run the tests.

@Cristiana959 can you point to the way tests are run?

**Comment by okko222** [comment]
So to check if a specific function is working i should review the GitHub Classroom Workflow.

**Comment by alexandruradovici** [comment]
Yes.
