### ISSUE TITLE
[rustybox] ls prints extra files

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#86]
La commande ls ne passe pas les tests et c'est toujours la meme probleme: ls prints extra files/directories. J'ai verifie avec les tests et, pour moi, les resultats ont le meme nombre des lignes. Est-ce qu'il y a un probleme avec les espaces? 
![ls_problem](https://user-images.githubusercontent.com/101063308/226599708-c294b458-850e-4aa6-94f5-f0d4e83e6991.png)

**Comment by alexandruradovici** [comment]
Looking into it.

**Comment by alexandruradovici** [comment]
The expected output is without the `lstest` folder:

```
modern family
TVshows
modern family/pritchett
...
```

Same as https://github.com/UPB-FILS-SdE2/questions/issues/83
