### ISSUE TITLE
[rustybox] ls issue

### ISSUE THREAD

**Issue by LauraNeamtu15** [UPB-FILS-SdE2/questions#88]
The same result as the original command does not pass the tests
![image](https://user-images.githubusercontent.com/122366887/227706490-f448e2f4-41e9-47cf-9419-61934ea90021.png)

**Comment by alexandruradovici** [comment]
The ls version that you have to implement works different from the `ls` command, it prints each file name on a different line. Your output should be:

```
-a
14:59
...
```
