### ISSUE TITLE
[rustybox] invalid command

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#89]
I keep having this problem. I have tried to return -1 in the main function as an Err(255) and with process::exit(255), yet they don't seem to work. Is there another way to return -1?
![image](https://user-images.githubusercontent.com/101063308/227768976-cf5dedce-379c-4d0b-9be3-e111c9118781.png)

**Comment by alexandruradovici** [comment]
You have to return -1, not 255. The data type should be `i32`. Take a look at https://doc.rust-lang.org/std/process/fn.exit.html.
