### ISSUE TITLE
New Bug at the last exercice

### ISSUE THREAD

**Issue by sudo-art** [UPB-FILS-SdE2/questions#9]
Hello! 

I wanted to point out that a bug occures in the last exercise, last requirement. It even displays me '_The cities were not stared correctly with the weather data'_. If I write 10 on the second position when I run the script, it saves it as 15 in the file, although I don't understand why.  If I write numbers less than 10, it saves them as they are...

I tested the code beforehand and it meets the requirement correctly

**Comment by sudo-art** [comment]
This morning I tried to retake the last task. _**I mention by now that I haven't changed the code of the script**_. What's funny this time is that 10 no longer turns into 15, it's saved correctly in the file, but the error message is still there... This bug is getting weirder and weirder

**Comment by ioanaculic** [comment]
You need to run the script several times and make sure the output is as expected.

**Comment by sudo-art** [comment]
I have been running the script for 25 times. The output has been each time according to the requirement, still the bug is persisting

**Comment by ioanaculic** [comment]
Can you post a screenshot of the output file? ONLY the output, NOT the script.

**Comment by sudo-art** [comment]
![Untitled2](https://user-images.githubusercontent.com/61539411/111076578-83526080-84f5-11eb-86a5-da7e331e2ea6.png)

**Comment by AbdelmadjidBOUR** [comment]
Hello all,
I have the same issue.

**Comment by ioanaculic** [comment]
You need to try the script with multiple different cities and temperatures. Also, try inserting cities that have a more complex name like Cluj-Napoca.

**Comment by AbdelmadjidBOUR** [comment]
I already did that, everything worked correctly. The problem here is when I used "**sudo uso check**" to check, it showed me this "_The cities were not stored correctly with the weather data_"

**Comment by sudo-art** [comment]
Exactly! It doesn't matter at all neither the name of the city, the value of the temperature or the status, nor the number of times the script had been run

**Comment by ioanaculic** [comment]
Again, please post the output file after you run the script multiple times with multiple different cities and temperatures.

**Comment by AbdelmadjidBOUR** [comment]
Also, when I enter an existing city with a different temperature and weather, the old one will be updated, so everything is working correctly.
![sudo](https://user-images.githubusercontent.com/79580257/111086964-59ae2f00-851f-11eb-8f46-4cb0a6aa9933.png)

**Comment by ioanaculic** [comment]
I would also need to see the weather.info file. The problem seems to be there, as you do not get the points for solving the first task.

**Comment by sudo-art** [comment]
There is no weather.info... But there is weather.sh which is the script to be run. The file in which the info is saved is called live.info

**Comment by ioanaculic** [comment]
To get the first 10 points out of 25 for this exercise you need to create a file called weather.info

**Comment by sudo-art** [comment]
> You need to try the script with multiple different cities and temperatures. Also, try inserting cities that have a more complex name like Cluj-Napoca.

I have tried in vain... It's a bug which prevents saving the content correctly... If you check the final output in the file every time after runnig the script with different parameters, it comes up as it should be. But if you check it after serveral times of running the script with different parameters, the output is: _Bucuresti 15 soare_ no matter what you have typed. In each case, the error message appears when calling the checker...

**Comment by sudo-art** [comment]
> To get the first 10 points out of 25 for this exercise you need to create a file called weather.info

Yes, I know that and I already did that. The bug appears at the last requirement...

**Comment by flaviabarbu-sa** [comment]
Evidence:

![Untitled8](https://user-images.githubusercontent.com/61539411/111174767-6169e400-85b0-11eb-9354-1b365589a3da.png)

![Untitled7](https://user-images.githubusercontent.com/61539411/111174785-65960180-85b0-11eb-90b9-284dfdb9906d.png)

**Comment by ioanaculic** [comment]
The checker erases all information once it finishes executing. Please run your script several times then print the weather.info file, without running the checker.

**Comment by sudo-art** [comment]
> To get the first 10 points out of 25 for this exercise you need to create a file called weather.info

That you kept mentioning in this discussion, all the steps I had done at the first requirement were suddenly gone. I had to retake them from 0. Now, if I try solve the last requirement, my previous work will be deleted for no reason which is not OK.

**Comment by AbdelmadjidBOUR** [comment]
I have the same issue with you @flaviabarbu-sa , I think we should add both scripts in the same file which is weather.sh and the same line as well.

**Comment by ioanaculic** [comment]
Just to be clear, to get all the points for task 7, you need to create a one-liner that solves both requirements.

**Comment by AbdelmadjidBOUR** [comment]
@ioanaculic exactly. Will give it a try. Thank you.

**Comment by AbdelmadjidBOUR** [comment]
The script worked perfectly but I'm still getting the same error.
![image](https://user-images.githubusercontent.com/79580257/111203279-173f2d80-85c5-11eb-96b9-b304dc50257f.png)

**Comment by sudo-art** [comment]
> The script worked perfectly but I'm still getting the same error.
> ![image](https://user-images.githubusercontent.com/79580257/111203279-173f2d80-85c5-11eb-96b9-b304dc50257f.png)

It's exactly the opposite... The long list of elements should have been in the file called weather.info and vice versa...

**Comment by AbdelmadjidBOUR** [comment]
@flaviabarbu-sa I don't think so. Read the task 7 again.

**Comment by sudo-art** [comment]
> @flaviabarbu-sa I don't think so. Read the task 7 again.

It's exactly as I said. The long list should be in weather.info and the one line list should be in live.info

**Comment by sudo-art** [comment]
> Just to be clear, to get all the points for task 7, you need to create a one-liner that solves both requirements.

I have just tried as you mentioned and the funny fact is that now it deletes all my files from the output directory. Therefore I have no output files where to save the info... Even though this happens, the checker has still accepted the fact that the first requirement has been solved

**Comment by sudo-art** [comment]
My script meets the requirements. I have tested it beforehand

**Comment by AbdelmadjidBOUR** [comment]
Finally it worked. (After I tried all possibilities).
@flaviabarbu-sa  Both files have long lists, it depends on the entries, just read the task 7 again especially the 2nd question. I hope it will work for you.

**Comment by sudo-art** [comment]
> > Just to be clear, to get all the points for task 7, you need to create a one-liner that solves both requirements.
> 
> I have just tried as you mentioned and the funny fact is that now it deletes all my files from the output directory. Therefore I have no output files where to save the info... Even though this happens, the checker has still accepted the fact that the first requirement has been solved

Now the output files are there. The problem is that there is no content saved although I've been running the script. The checker still accepted the first requirement as being solved. This is more awkward than I thought it could be

**Comment by sudo-art** [comment]
> Finally it worked. (After I tried all possibilities).
> @flaviabarbu-sa Both files have long lists, it depends on the entries, just read the task 7 again especially the 2nd question. I hope it will work for you.

I'm glad it worked for you. But according to the requirement, the second output file must contain only one line: _Après d'exécuté les commandes ./weather.sh Bucuresti 10 soare et ./weather.sh Bucuresti 8 ploaie, le fichier live.info contiendra la ligne Bucuresti 8 ploaie._

**Comment by sudo-art** [comment]
Therefore, it should be no long list on there...

**Comment by sudo-art** [comment]
> > > Just to be clear, to get all the points for task 7, you need to create a one-liner that solves both requirements.
> > 
> > 
> > I have just tried as you mentioned and the funny fact is that now it deletes all my files from the output directory. Therefore I have no output files where to save the info... Even though this happens, the checker has still accepted the fact that the first requirement has been solved
> 
> Now the output files are there. The problem is that there is no content saved although I've been running the script. The checker still accepted the first requirement as being solved. This is more awkward than I thought it could be

As I tried once more, my output files are gone again... The checker still accepted the first requirement as being solved. I don't get why the files disappear

**Comment by AbdelmadjidBOUR** [comment]
> 
> 
> > Finally it worked. (After I tried all possibilities).
> > @flaviabarbu-sa Both files have long lists, it depends on the entries, just read the task 7 again especially the 2nd question. I hope it will work for you.
> 
> I'm glad it worked for you. But according to the requirement, the second output file must contain only one line: _Après d'exécuté les commandes ./weather.sh Bucuresti 10 soare et ./weather.sh Bucuresti 8 ploaie, le fichier live.info contiendra la ligne Bucuresti 8 ploaie._

No, that's  only an example.

**Comment by sudo-art** [comment]
> > > Finally it worked. (After I tried all possibilities).
> > > @flaviabarbu-sa Both files have long lists, it depends on the entries, just read the task 7 again especially the 2nd question. I hope it will work for you.
> > 
> > 
> > I'm glad it worked for you. But according to the requirement, the second output file must contain only one line: _Après d'exécuté les commandes ./weather.sh Bucuresti 10 soare et ./weather.sh Bucuresti 8 ploaie, le fichier live.info contiendra la ligne Bucuresti 8 ploaie._
> 
> No, that's only an example.

OK. Thank you for the hint! I thought the second output file must contain only one line

**Comment by sudo-art** [comment]
> > > > Finally it worked. (After I tried all possibilities).
> > > > @flaviabarbu-sa Both files have long lists, it depends on the entries, just read the task 7 again especially the 2nd question. I hope it will work for you.
> > > 
> > > 
> > > I'm glad it worked for you. But according to the requirement, the second output file must contain only one line: _Après d'exécuté les commandes ./weather.sh Bucuresti 10 soare et ./weather.sh Bucuresti 8 ploaie, le fichier live.info contiendra la ligne Bucuresti 8 ploaie._
> > 
> > 
> > No, that's only an example.
> 
> OK. Thank you for the hint! I thought the second output file must contain only one line

I followed your example. Now I get that I have permission denied for the first output file... Again, when I access the path to display them, they're gone

**Comment by ioanaculic** [comment]
I will mention it again, please don't try to access the files generated after running the checker. Those are some files that we forgot to delete and are not relevant for how your homework behaves or the points that you get.

**Comment by sudo-art** [comment]
> I will mention it again, please don't try to access the files generated after running the checker. Those are some files that we forgot to delete and are not relevant for how your homework behaves or the points that you get.

I didn't try to access files generated by the checker. On the contrary, the checker deletes the output files created before running it. As a message, now I'm displayed that _live.info does not contain the correct data._ This is happening no matter if I make the script save multiple lines or just one line with the respective parameters in live.info

**Comment by ioanaculic** [comment]
That means that the file you generate is not correct. Make sure you don't store any city twice and that all the information about the weather is updated each time you run the script.

**Comment by sudo-art** [comment]
> That means that the file you generate is not correct. Make sure you don't store any city twice and that all the information about the weather is updated each time you run the script.

I'm sure I didn't store any name twice. As for the update, I cannot check because the _weather.info_ and _live.info_ files are gone each time I run the cheker.

**Comment by ioanaculic** [comment]
You can check by manually running the script multiple times.
