### ISSUE TITLE
[rustybox] panic only in tests

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#90]
I executed manually all the commands in the test file "cp rename directory" and they did not cause any problems and copied the directory contents successfully, yet when the test runs it, the program panics and I don't understand why. 
![image](https://user-images.githubusercontent.com/101063308/228035380-10fc48e0-f5a7-4be0-8b48-ab90f1ad2e73.png)

**Comment by alexandruradovici** [comment]
This test copies a whole directory into another directory. Is tis what you are doing?

You need to figure out which function fails and why the file or directory does not exist.

**Comment by mihaicostin34** [comment]
yes, and it doesn't panic
