### ISSUE TITLE
[rustyshell] stderr

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#91]
Although I redirect stderr and stdout using the same instructions (modifying only where needed), one passes the tests while the other doesn't. This is what the test result shows
![image](https://user-images.githubusercontent.com/101063308/230731271-7f283baa-2597-44a9-a705-f483d33dec80.png)

**Comment by alexandruradovici** [comment]
You should not write to the output anything, but you seems to output two lines of text.

**Comment by alexandruradovici** [comment]
Running this in your code 

```
$ ls /inexistent
```

panics with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:167:77
```

This might be why the test fails. Please try the commands form the tests locally.
