### ISSUE TITLE
tp2 - intrebari

### ISSUE THREAD

**Issue by maradraghici** [UPB-FILS-SdE2/questions#92]
Care este diferenta dintre cele doua print-uri?

<img width="443" alt="Screenshot 2023-04-10 224711" src="https://user-images.githubusercontent.com/126445298/230984907-049d01e0-cf81-4403-8f8c-fd82a9bc96af.png">

Cum functioneaza referintele acestea?
<img width="192" alt="image" src="https://user-images.githubusercontent.com/126445298/230985297-576df847-2647-49c4-b8e4-fe27cae3b6ca.png">

**Comment by alexandruradovici** [comment]
Afiseaza `mode` normal si apoi cu :b si :o, ce iti afiseaza daca le incerci?

In loc de mode, pune un numar mai mare ca 20, vezi ce iti scrie.

Nu e referinta, e si pe biti https://en.m.wikipedia.org/wiki/Bitwise_operation.
