### ISSUE TITLE
tp4 - intrebari

### ISSUE THREAD

**Issue by maradraghici** [UPB-FILS-SdE2/questions#93]
As avea nevoie de cateva explicatii aici (ex4)
<img width="338" alt="image" src="https://user-images.githubusercontent.com/126445298/230986722-76c57665-6320-4d51-9013-8942132d72b2.png">

De ce este nevoie de {child} aici? Sau cum functioneaza? (ex5)
<img width="272" alt="image" src="https://user-images.githubusercontent.com/126445298/230986959-9d549ae4-02e1-4363-b8b1-b3778ff66067.png">

Nu inteleg cum functioneaza partea aceasta (si in special de ce este 1 al doilea parametru al functiei, cum functioneaza?) (tot ex 5):
<img width="428" alt="image" src="https://user-images.githubusercontent.com/126445298/230987281-5cf367d8-89ef-4839-8da0-3d15271ac360.png">

**Comment by alexandruradovici** [comment]
> As avea nevoie de cateva explicatii aici (ex4)
> 
> <img width="338" alt="image" src="https://user-images.githubusercontent.com/126445298/230986722-76c57665-6320-4d51-9013-8942132d72b2.png">
> 
> 
Te rog fi mai clara cu ce nu e clar.
> 
> De ce este nevoie de {child} aici? Sau cum functioneaza? (ex5)
> 
> <img width="272" alt="image" src="https://user-images.githubusercontent.com/126445298/230986959-9d549ae4-02e1-4363-b8b1-b3778ff66067.png">
> 
> 
`fork` intoarce un enum de tipul `ForkResult` https://docs.rs/nix/latest/nix/unistd/enum.ForkResult.html care are doua variante. `Parent` are in interior o structura cu un field `child` si asa poti lua valoarea lui. Din enum poti lua payload-ul doar cu match. Uita-te cu atentie la documentatia https://docs.rs/nix/latest/nix/unistd/fn.fork.html.
> 
> Nu inteleg cum functioneaza partea aceasta (si in special de ce este 1 al doilea parametru al functiei, cum functioneaza?) (tot ex 5):
> 
> <img width="428" alt="image" src="https://user-images.githubusercontent.com/126445298/230987281-5cf367d8-89ef-4839-8da0-3d15271ac360.png">
> 
> 
Vezi https://www.geeksforgeeks.org/dup-dup2-linux-system-call/amp/ pentru a intelege ce fac `dup` si `dup2`. Acel 1 reprezinta stdout (ecranul).
> '
