### ISSUE TITLE
[scheduler] different test results

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#94]
I have a different branch in the folder repository where I also have the tests so that I can run them without pushing every time I make small changes. I also have the main branch, without tests. I pushed it and it did not pass some tests, like this one:
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/05459800-fcb2-4bcf-867d-6184e42e9ebc)
But when I run the same test locally, the result is different and correct
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/72f4c748-16ff-40b8-baa5-4c489931d5a4)
Is it ok if I just merge the branch with the tests and push from there? Or is there a problem for the checker if the tests exist locally?

**Comment by alexandruradovici** [comment]
Your results are not correct. The list of processes shows thae stare of the processes when the new process is scheduled or when the processor sleeps. You are showing the list after the process finishes.

The checker deletes your tests.
