### ISSUE TITLE
[schelduler] File not found for module 'scheduler/schedulers/round_robin_cfs'

### ISSUE THREAD

**Issue by crisitinagogoase** [UPB-FILS-SdE2/questions#95]
![Screenshot 2023-05-13 211613](https://github.com/UPB-FILS-SdE2/questions/assets/115778028/eb485d35-e2f6-4c79-a836-1480894d0734)

In fisierul lib.rs din 'scheduler/src' imi afiseaza eroarea ca nu vede fisierele corespunzatoare modulelor, desi le-am importat in 'scheduler/src//schedulers/mod.rs'.

**Comment by alexandruradovici** [comment]
Acestea sunt submodule ale lui `schedulers`. In lib rs pui `mod schedulers` iar in `mod.rs` le pui pe astea.
