### ISSUE TITLE
[bug] Checker bug

### ISSUE THREAD

**Issue by mihaivladimir25** [UPB-FILS-SdE2/questions#96]
I encountered the problem of translating certain requirements. For example, in Task 4 exercise 1 we were told that symbolic links should be called part1 and part2. I did this and the test was not passing, then I looked at theme 1 from the romanian version and saw that it said partea 1 and partea 2, I changed that way and passed the test. Do I have to comply with the requirement in French or follow the tests?

**Comment by Cristiana959** [comment]
You use the romanian version. I've updated the text of the homework
