### ISSUE TITLE
[rustyloader] Setup problems

### ISSUE THREAD

**Issue by mihaicostin34** [UPB-FILS-SdE2/questions#97]
The cargo command was not recognized, so I installed rust with 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
and also ran the command 
rustup target add i686-unknown-linux-gnu
Now, when I run the command cargo run, I get this error
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/76a6ab47-f064-409e-aa44-4b99abc02159)
followed by a big block of text and then this
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/387b8aa4-1e92-4156-a505-413276c620e9)

**Comment by alexandruradovici** [comment]
You have to install gcc using `sudo apt-get install build-essential`. Make sure to run onve before `sudo apt-get update`.

**Comment by mihaicostin34** [comment]
This is the log
![image](https://github.com/UPB-FILS-SdE2/questions/assets/101063308/e404a5b3-3d90-43d3-9785-970b70b0a65c)
The same thing as before happens when I run cargo run or cargo build

**Comment by alexandruradovici** [comment]
Try runnging `sudo apt-get install gcc g++`.

**Comment by alexandruradovici** [comment]
My bad, you are missing lgcc, try installing it https://howtoinstall.co/en/libgcc-4.8-dev. The version should not matter.

**Comment by alexandruradovici** [comment]
Take a look at `.github/classroom/autograding.json` at the first command that it runs. This installs all the dependencies.

**Comment by mihaicostin34** [comment]
Manually running the first command in autograding.json worked. Now the project builds.
