### ISSUE TITLE
Login Issues devoir1 

### ISSUE THREAD

**Issue by alinalaz** [UPB-FILS-SdE2/questions#98]
Buna ziua! Am o  problema la logarea in masina virtuala, imi arata ca as fi logata as null, desi codul din CLI a fost validat. Am reinstalat masina si am acelasi rezultat. Ma puteti juta va rog?
![VirtualBox_USO Teme_31_05_2023_16_52_54](https://github.com/UPB-FILS-SdE2/questions/assets/126449901/f42e3053-dc44-4d88-8d15-a4503d11629a)

**Comment by alexandruradovici** [comment]
Buna, e posibil sa nu ai Internet pe masina virtuala. Te rog ruleaza ping 8.8.8.8 si ping temeuso.cs.pub.ro si pune aici ce afiseaza.

**Comment by alinalaz** [comment]
![Vm screen](https://github.com/UPB-FILS-SdE2/questions/assets/126449901/f0deb8cb-b225-4ebb-8a35-9a0b36ba509a)
